# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          와이즈버즈 기술 블로그
paginate:       5
baseurl:        ""
url:            "https://wisebirds-tech.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         WisebirdsTech
  url:          http://adwitt.co
  email:        tech@adwitt.com

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/wisebirds-tech

# Gems
gems:
  - jekyll-paginate
